version: '3.8'

services:
  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes

  api:
    build:
      context: .
      dockerfile: docker/api.Dockerfile
    ports:
      - '3001:3001'
    environment:
      - NODE_ENV=production
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    env_file:
      - .env
    depends_on:
      - redis
    volumes:
      - ./apps/api:/app/apps/api
      - /app/node_modules
    restart: unless-stopped

  web:
    build:
      context: .
      dockerfile: docker/web.Dockerfile
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://api:3001
    env_file:
      - .env
    depends_on:
      - api
    volumes:
      - ./apps/web:/app/apps/web
      - /app/node_modules
    restart: unless-stopped

volumes:
  redis-data:


